version: "3.9"
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 

  app:
    build: .
    container_name: node-app
    command: pnpm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
